### ISSUE TITLE
Name Limit(Suggestion)

### ISSUE THREAD

**Issue by Zetenatom** [thawkin3/chat-sockets#10]
Limit the number of characters in a persons username. As it is currently usernames can be obscenely long. I would suggest somewhere around 20 characters.

**Comment by thawkin3** [comment]
@Zetenatom Good suggestion! I'll get on that.

**Comment by thawkin3** [comment]
@Zetenatom Ok this should be implemented now. The new rules I set are that usernames must be 3-20 characters and be alphanumeric characters only, so no spaces in the usernames either. Can you re-test? Thanks!
