### ISSUE TITLE
Post Limit(Suggestion)

### ISSUE THREAD

**Issue by Zetenatom** [thawkin3/chat-sockets#11]
As it is currently there seems to be no limit to the amount of text and individual can post at one time. We noticed this when we posted a movie script in the chat, and after some time it did post it. When then edited the script to include about double if not triple the amount of characters and posted it again. While it probably isn't too much of an issue, I would suggest a limit.

**Comment by thawkin3** [comment]
@Zetenatom Haha that's awesome, great movie script choice. This is a good suggestion. I think Slack and maybe even Discord limits messages to 2000 characters, so I could do the same.

**Comment by thawkin3** [comment]
@Zetenatom Ok this is implemented now. Messages can be 2000 characters long, but not 2001 or longer. If you do enter text that is longer than 2000 characters, the app shows some warning text below the input field, and hitting Enter doesn't post the messages. Can you re-test? Thanks as always for the good suggestions!
