### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by Cborek** [thawkin3/chat-sockets#12]
There is currently no limit to the number of messages that a user can post within a given time frame. This makes it easy to spam messages in the chat. I'd suggest putting a 'timeout' on users who post x number of messages within a certain time frame.

**Comment by thawkin3** [comment]
@Cborek I'm torn on this one. You're right that there's potential to spam the app to the point where it's annoying (or even unusable) for other people, but as far as I know other chat applications like Slack and Discord don't have similar timeout periods. I'd consider Slack a "thought leader" in the industry, so I'd be curious to know if they've considered this at all and if they have, why the decided against it.

There's only one channel in Chat Sockets, so there's not really a way to tune out the noise, but in a more sophisticated app like Slack or Discord you can create different channels, even private channels, so it'd be possible to get away from the spammy user. Or I'm sure there's even administrator stuff for those channels where you could ban a user if they're known for abusing the app.

All of these things would be cool to implement, but given it's just a side project and more of a demo concept I don't know how much work I want to put into it and which new features to add.

What do you think?

**Comment by Cborek** [comment]
@thawkin3 Yeah, it doesn't look like either application actually puts users in timeout for spamming. I do know that Discord just issues a warning when users post too much too quickly. I'd say implementing something like that would be great if possible.

When looking at Slack, I can't find much of any information relating to this discussion. But I am curious and will look into it more. When it comes to Discord, I know that users have a lot of options for moderation and using bots to deal with users that spam and do similar things. Including putting users into timeout for a period of time. So perhaps Discord's (and maybe Slacks as well) mentality is that it's just up to the user to deal with it.

**Comment by thawkin3** [comment]
@Cborek I did some reading today and found this article from Slack on rate limiting: https://api.slack.com/docs/rate-limits

It looks like they limit message posting to 1 message per second "per app per workspace". Or further down they describe it as:

> In general, applications may post no more than one message per second per channel, whether a message is posted via chat.postMessage, an incoming webhook, or one of the many other ways to send messages in to Slack.

And then regarding other measures they take to prevent spam, at the very bottom of the documentation they say:

> We reserve the right to rate limit other functionality to prevent abuse, spam, denial-of-service attacks, or other security issues. Where possible we'll return a descriptive error message, but the nature of this type of rate limiting often prevents us from providing more information.

So I think for this, I'm going to just close this issue. Like we said, in a production-ready app there would be better rate limiting or even a moderation tool where you could block a user or put them in a time out, but for a demo app like this one, it doesn't seem worth it.

Great suggestion though, and definitely something you'd want to implement in the real world!
